services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=seu_banco'
      - 'POSTGRES_PASSWORD=sua_senha'
      - 'POSTGRES_USER=seu_usuario'
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=sua_senha'
      - 'RABBITMQ_DEFAULT_USER=seu_usuario'
    ports:
      - '5672'
volumes:
  pgdata: